export const contractsData = [
  {
    state: "Pernambuco",
    projects: [
      {
        name: "Corte e Religação DRI",
        manager: "Moacir",
        validity: "17/12/2027",
        director: "Tecio",
        client: "Compesa",
      },
      {
        name: "Recuperação de Débito",
        manager: "Moacir",
        validity: "31/01/2026",
        director: "Tecio",
        client: "Compesa",
      },
      {
        name: "Cobrança Administrativa e Judicial",
        manager: "Moacir",
        validity: "24/12/2026",
        director: "Tecio",
        client: "Compesa",
      },
      {
        name: "Requalificaçãao DRM",
        manager: "Marcos",
        validity: "31/07/2027",
        director: "Dr. Paulo",
        client: "Compesa",
      },
      {
        name: "Consórcio DRM",
        manager: "Nobre",
        validity: "11/09/2026",
        director: "Tecio",
        client: "Compesa",
      },
      {
        name: "Contrato Prefeitura de Ipojuca",
        manager: "Dr. Caio",
        validity: "18/08/2027",
        director: "Dr. Caio",
        client: "Prefeitura de Ipojuca",
      },
      {
        name: "Creche Cyro de Andrade",
        manager: "Wagner",
        validity: "31/12/2026",
        director: "Dr. Paulo",
        client: "Prefeitura de Recife",
      },
      {
        name: "Suape",
        manager: "Thalles",
        validity: "29/12/2025",
        director: "Dr. Paulo",
        client: "Porto de Suape",
      },
      {
        name: "Fundarpe - Ginasio Pernambucano",
        manager: "Gutenberg",
        validity: "18/19/2026",
        director: "Dr. Paulo",
        client: "Gov - PE",
      },
      {
        name: "Fundarpe - (MAC)",
        manager: "Gutenberg",
        validity: "17/06/2026",
        director: "Dr. Paulo",
        client: "Gov - PE",
      },
      {
        name: "Fundarpe - Museu do Trem",
        manager: "Gutenberg",
        validity: "17/06/2026",
        director: "Dr. Paulo",
        client: "Gov - PE",
      },
    ],
  },
  {
    state: "Sergipe",
    projects: [
      {
        name: "Iguá - Corte e Religação",
        manager: "Nobre",
        validity: "28/02/2026",
        director: "Tecio",
        client: "Iguá",
      },
      {
        name: "Iguá - Cadastro e Verificação de Consumo",
        manager: "Nobre",
        validity: "02/05/2026",
        director: "Tecio",
        client: "Iguá",
      },
      {
        name: "Iguá - Hidrometro",
        manager: "Nobre",
        validity: "31/03/2026",
        director: "Tecio",
        client: "Iguá",
      },
      {
        name: "Iguá - Sondagem",
        manager: "Nobre",
        validity: "16/01/2026",
        director: "Tecio",
        client: "Iguá",
      },
      {
        name: "Iguá - Instalação de Sensores",
        manager: "Nobre",
        validity: "10/05/2026",
        director: "Tecio",
        client: "Iguá",
      },
      {
        name: "Iguá - Recadastramento",
        manager: "Nobre",
        validity: "24/06/2026",
        director: "Tecio",
        client: "Iguá",
      },
      {
        name: "Iguá - Recadastramento Fte",
        manager: "Nobre",
        validity: "02/01/2027",
        director: "Tecio",
        client: "Iguá",
      },
    ],
  },
  {
    state: "Alagoas",
    projects: [
      {
        name: "BRK - Hidrometro",
        manager: "Hugo",
        validity: "10/05/2026",
        director: "Tecio",
        client: "BRK",
      },
      {
        name: "BRK - Pavimentação Operacional",
        manager: "Hugo",
        validity: "09/10/2030",
        director: "Tecio",
        client: "BRK",
      },
      {
        name: "BRK - Pavimentação Comercial",
        manager: "Hugo",
        validity: "24/06/2026",
        director: "Tecio",
        client: "BRK",
      },
      {
        name: "BRK - Fiscalização",
        manager: "Hugo",
        validity: "17/06/2026",
        director: "Tecio",
        client: "BRK",
      },
      {
        name: "Verde Alagoas",
        manager: "Hugo",
        validity: "26/05/2026",
        director: "Tecio",
        client: "Verde Alagoas",
      },
      {
        name: "Companhia Saneamento de Alagoas - Casal",
        manager: "Hugo",
        validity: "24/04/2029",
        director: "Tecio",
        client: "Casal",
      },
    ],
  },
  {
    state: "Piauí",
    projects: [
      {
        name: "Aegea",
        manager: "Moacir",
        validity: "08/10/2026",
        director: "Tecio",
        client: "Aegea",
      },
    ],
  },
];
